// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWz_s4q1Gx8acf2gC8wPyWfH6sY0gdNrM',
    appId: '1:901909182015:web:a3320d754b68da74c76a8a',
    messagingSenderId: '901909182015',
    projectId: 'todo-app-ed72a',
    authDomain: 'todo-app-ed72a.firebaseapp.com',
    storageBucket: 'todo-app-ed72a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1fOtDhahVXg5x5HKuLXJNusp2mJJJ3s4',
    appId: '1:901909182015:android:f46ff3c5d1ad5f09c76a8a',
    messagingSenderId: '901909182015',
    projectId: 'todo-app-ed72a',
    storageBucket: 'todo-app-ed72a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp92GentLbkIAoVgYI6VAQ55fU4I_Ob8g',
    appId: '1:901909182015:ios:3fb4f4c097959055c76a8a',
    messagingSenderId: '901909182015',
    projectId: 'todo-app-ed72a',
    storageBucket: 'todo-app-ed72a.appspot.com',
    iosClientId: '901909182015-671aa6pqsvggibn79u01dgu2s6jv8lrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp92GentLbkIAoVgYI6VAQ55fU4I_Ob8g',
    appId: '1:901909182015:ios:3fb4f4c097959055c76a8a',
    messagingSenderId: '901909182015',
    projectId: 'todo-app-ed72a',
    storageBucket: 'todo-app-ed72a.appspot.com',
    iosClientId: '901909182015-671aa6pqsvggibn79u01dgu2s6jv8lrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
